services:
  frontend:
    container_name: frontend
    build:
      context: ./
    ports:
      - 3000:5173
    restart: always
    tty: true
    volumes:
      - ./frontend:/app
      - react-node_modules:/app/node_modules
volumes:
  react-node_modules: